// flow-typed signature: 2948d44968ac2b891a84e52d7a0ee8f5
// flow-typed version: <<STUB>>/pretty_v2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pretty/index' {
  declare module.exports: $Exports<'pretty'>;
}
declare module 'pretty/index.js' {
  declare module.exports: $Exports<'pretty'>;
}
